version: "3.8"

services:
  db:
    image: postgres
    # persist data beyond lifetime of container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=tiktok_insights
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    # persistent storage
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
  web:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  celery:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A tiktok_insights worker -l INFO --beat --concurrency 2
    volumes:
      - .:/code
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
